apiVersion: tackle.konveyor.io/v1alpha1
kind: Addon
metadata:
  name: windup
  namespace: konveyor-tackle
spec:
  image: quay.io/konveyor/tackle2-addon-windup:latest
  imagePullPolicy: Always
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 0
      memory: 0

