name: Test execution

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

jobs:
  test-stage0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: start-minikube
        uses: konveyor/tackle2-operator/.github/actions/start-minikube@main
        with:
          memory: 6500M
      - name: install-tackle
        uses: konveyor/tackle2-operator/.github/actions/install-tackle@main
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: make test-stage0
  test-stage1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: start-minikube
        uses: konveyor/tackle2-operator/.github/actions/start-minikube@main
        with:
          memory: 6500M
      - name: install-tackle
        uses: konveyor/tackle2-operator/.github/actions/install-tackle@main
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: make test-stage1
  test-stage2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: start-minikube
        uses: konveyor/tackle2-operator/.github/actions/start-minikube@main
        with:
          memory: 6500M
      - name: install-tackle
        uses: konveyor/tackle2-operator/.github/actions/install-tackle@main
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: make test-stage2
