name: Test nightly TIER1

on:
  schedule:
    - cron: '14 1,13 * * *'
      
jobs:
  test-tier1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: start-minikube
        uses: konveyor/tackle2-operator/.github/actions/start-minikube@main
        with:
          memory: 6500M
      - name: install-tackle
        uses: konveyor/tackle2-operator/.github/actions/install-tackle@main
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install dependencies
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo
      - run: HUB_BASE_URL="http://$(minikube ip)/hub" DEBUG=1 make test-tier1
      - run: HUB_BASE_URL="http://$(minikube ip)/hub" ginkgo -v --focus "Jira connection"
        env:
          JIRA_CLOUD_USERNAME: ${{ secrets.JIRA_CLOUD_USERNAME }}
          JIRA_CLOUD_PASSWORD: ${{ secrets.JIRA_CLOUD_PASSWORD }}
          JIRA_CLOUD_URL: ${{ secrets.JIRA_CLOUD_URL }}
          JIRA_SERVER_URL: ${{ secrets.JIRA_SERVER_URL }}
          JIRA_SERVER_USERNAME: ${{ secrets.JIRA_SERVER_USERNAME }}
          JIRA_SERVER_PASSWORD: ${{ secrets.JIRA_SERVER_PASSWORD }}
          JIRA_SERVER_TOKEN: ${{ secrets.JIRA_SERVER_TOKEN }}
